-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmzDDvkITlLvtkPmv
ayoGN/w0mZF+NyG8t1hbRCzwcwigCgYIKoZIzj0DAQehRANCAAQS5KIheFxuWzI0
cQBebhbj5sTjY/UYqJrhH3K4ZUfLpISuxEILWFVcLOgMR4MmmP4gECbmgIgkqcos
GWb7ySVJ
-----END PRIVATE KEY-----