require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'
install! 'cocoapods', :deterministic_uuids => false

target 'justo' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'
  
  # Add permissions pods
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  pod 'Permission-Calendars', :path => "#{permissions_path}/Calendars"

  # Add React Native File System pod
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  # Flags change depending on the env values
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Test target (optional)
  target 'justoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Post-install hooks to apply bitcode setting and fix any issues
  post_install do |installer|
    # Disable bitcode for all targets (app and pods)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end

    # Call the React Native post-install hook
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )

    # Optional: Fix for Xcode 12.5 and M1 Mac issues (if needed)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
